### ISSUE TITLE
SVScore generates multiple VCFs per input file

### ISSUE THREAD

**Issue by archanaraja** [lganel/SVScore#6]
Hi , Is it normal for SVScore to generate multiple VCFs per input? I thought that it finally generates one output VCF per input.  Could you tell me why this is happening? I'm testing it on my laptop with 16 GB memory and has 4 cores.

Thanks,
Archana

**Comment by lganel** [comment]
Hi Archana,
Could you share the command you used to call SVScore? If you're using `split.pl`, you should of course be seeing multiple input and output files, but otherwise you should only be getting one output file per input.
Another possibility is that you're looking in the `svscoretmp` directory. While it runs, SVScore generates some temporary files in a subdirectory called `svscoretmp`, some of which are VCF files. But unless you're supplying the `-d` flag, SVScore should clean these up when it terminates.
I'm also curious as to the filenames of the extra VCF output files you're seeing. If you could share those, it might help me diagnose the issue.
Thanks!
Liron

**Comment by archanaraja** [comment]
Hi Liron, Thanks for following up on this.  Yes I was looking into the tmp svscoretmp dir below are the files I see
lr_only1568938578.50622.sort.vcf
lr_only1568938578.50622.preprocess.bedpe
lr_only1568940523.90302.sort.vcf.gz
lr_only1568940523.90302.preprocess.bedpe
lr_only1568940642.22113.sort.vcf.gz
lr_only1568940642.22113.preprocess.bedpe
lr_only1568941052.03972.sort.vcf.gz
lr_only1568941052.03972.preprocess.bedpe
lr_only1568941202.04311.sort.vcf.gz
lr_only1568941202.04311.preprocess.bedpe
lr_only1568941202.04311.out.bedpe

The command I used to run SVscore was ./svscore.pl -dv -o top10weighted -e refGene.exons.bed -f refGene.introns.bed -c whole_genome_SNVs.tsv.gz -i inputs/lr_only.vcf
Where are my finalized results ,  how should I interpret these outputs?
Thanks,
Archana

**Comment by lganel** [comment]
Hi Archana,

These are all temporary files and should be ignored. In fact, you can safely delete that entire directory. These files are only being kept because you are supplying the `-d` flag in your command, which runs SVScore in debug mode.
Your final output should be written to standard output (i.e. the shell). If you want it in a file, you can redirect it, like this: `./svscore.pl -dv -o top10weighted -e refGene.exons.bed -f refGene.introns.bed -c whole_genome_SNVs.tsv.gz -i inputs/lr_only.vcf  > inputs/lr_only.svscore.vcf`.
Are you getting any output or errors at the command line when you run your command? If not, there is a different issue, and I'd recommend you send me a slice of your VCF.

Liron

**Comment by archanaraja** [comment]
Great thank you so much Liron. I didn’t realize I have to redirect it to a file . I don’t think I see any issues then .  Do you have any recommendations for the -o flag ? I’m going with the default . I would also love to hear about the easiest way I can prioritize outputs ( any score cutoff you recommend or that has worked for you )
Thanks a lot for the help .
Archana

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lganel** [comment]
Glad that solved your problem!
As for score cutoffs and `-o` suggestions, these may depend on your specific application.
In our paper (https://academic.oup.com/bioinformatics/article/33/7/1083/2748212), most of our analyses were done using the `top10weighted` operation (the default), which worked well for our purposes.
I definitely wouldn't recommend using a hard score cutoff, though that may depend on your specific application. Again, I'd recommend you check out the paper, where we used a variant's score percentile within our callset to predict its pathogenicity.
Hope this helps!
Liron

**Comment by archanaraja** [comment]
Thank you so much for the information.

Archana
________________________________
